### ISSUE TITLE
What is the role of typedi in this project?

### ISSUE THREAD

**Issue by moltar** [kjaenicke/shipstation-node#2]
It seems to be unnecessary for a clean abstraction.

And feels like should be more of a project dependency.

Thanks.

**Comment by kjaenicke** [comment]
Thanks @moltar! You're absolutely right, in fact, typedi and reflect-metadata both can be removed. I'll submit a PR & release a new version once I have those removed.

**Comment by kjaenicke** [comment]
Unused deps have been removed. Published in v0.7.0. Thanks again for submitting the issue!
